name: 'PR Title Checker'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '\d+:? (.+)'
          allowed_prefixes: 'feature/NNL-,bug/NNL-,NNL-'
          prefix_case_sensitive: false
